// <auto-generated />
using LoanApp.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanApp.Migrations
{
    [DbContext(typeof(LoanContext))]
    [Migration("20240319133046_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoanApp.Models.BikeLoanRequest", b =>
                {
                    b.Property<string>("BikeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("BikePrice")
                        .HasColumnType("integer");

                    b.HasKey("BikeName");

                    b.ToTable("bikeloanrequests");
                });

            modelBuilder.Entity("LoanApp.Models.CarLoanRequest", b =>
                {
                    b.Property<string>("CarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CarPrice")
                        .HasColumnType("integer");

                    b.HasKey("CarName");

                    b.ToTable("carloanrequests");
                });
#pragma warning restore 612, 618
        }
    }
}
